name: Tests CI

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
            - reopened
            - edited

jobs:
    test:
        runs-on: ubuntu-latest

        # prevents run tests when "WIP"
        if: ${{ !contains(github.event.pull_request.title, 'WIP') }}

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Uses node ${{matrix.node-version}}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{matrix.node-version}}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm run test
